### ISSUE TITLE
Auto start for clock.py on boot froze

### ISSUE THREAD

**Issue by sigmasnyc88** [Boeeerb/PiGlow#14]
I entered each command as you entered on the step by step to configure an auto start for the clock in binary on boot for the Piglow. It stops the boot at 

[ ok ] Starting OpenBSD Secure Shell server: sshd.

please help me

**Comment by tommybobbins** [comment]
Hello Sigmasync88,

Please could you ssh into your Raspberry Pi, stop the script using 
    /etc/init.d/clock stop
Then please could you try and start the script manually and see if it works:
sudo python /home/pi/piglow/clock.py

Please could you let us know what result that gives? We've put some new instructions into the README which might help you.

Ta,

tommybobbins
