### ISSUE TITLE
Adding Pi B+ to the piglow.py script

### ISSUE THREAD

**Issue by SalvorinFex** [Boeeerb/PiGlow#18]
HI there

I am getting an **_init**_ error when trying to run your python scripts on a Model B+ Pi.

sudo python cpu.pyUnable to determine Raspberry Pi revision.
Traceback (most recent call last):
  File "cpu.py", line 13, in <module>
    piglow = PiGlow()
  File "/home/pi/piglow/piglow.py", line 30, in **init**
    self.bus = SMBus(i2c_bus)
UnboundLocalError: local variable 'i2c_bus' referenced before assignment

Can this be added to the *.py files?

Sal

**Comment by qkpham** [comment]
I've changed the RPI_REVISION in piglow.py to 3 on i2c bus 1 to make it work on my B+. I've used benleb github files.

elif rpi.RPI_REVISION == 2:
            i2c_bus = 1

TO 

elif rpi.RPI_REVISION == 3:
            i2c_bus = 1

**Comment by eddieishere** [comment]
Thanks qkpham!

**Comment by DougieLawson** [comment]
It would be better to future proof the code with

elif rpi.RPI_REVISION >= 2: # check for B or B+

It will only break if some later version (supported by RPi.GPIO) doesn't use i2c-1 for the i2c bus.

**Comment by Boeeerb** [comment]
Thanks for bringing this up guys, I've been a bit slow on the B+ uptake.

Rev 3 has been added
