### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ErikLentz** [Boeeerb/PiGlow#20]
I found that after a recent firmware update, I would get this error when attempting to use any PiGlow i2c python script:

`IOError: [Errno 2] No such file or directory`

I found the solution to be to add the line `dtparam=i2c1=on` to my /boot/config.txt

You may want to add this to the readme.

**Comment by timmattison** [comment]
@smeggysmeg I ran into the same problem but adding that parameter to my config.txt and rebooting didn't fix the issue.  Are there any other steps you took to resolve this?

**Comment by electronicsguy** [comment]
@timmattison   try  `dtparam=i2c_arm=1`  and use sudo to run the script  `sudo python /home/pi/piglow/test.py`

**Comment by K7TRY** [comment]
I resolved this issue on a RPi3 by installing RPi.GPIO. 

sudo apt-get install RPi.GPIO
